{% set version = "0.6.2" %}

package:
  name: xesmf
  version: {{ version }}

source:
  url: https://github.com/pangeo-data/xESMF/releases/download/v{{ version }}/xesmf-{{ version }}.tar.gz
  sha256: 21e02c490f0c0ecb2a2ffdb666796faf72a8610a0020a436be0fa55ddc9b3295

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools >=30.3.0
    - setuptools_scm
  run:
    - python >=3.6
    - esmpy >=8.0.0
    - xarray >=0.16.2
    - shapely
    - cf_xarray >=0.5.1
    - sparse

test:
  imports:
    - xesmf
  commands:
    - pip check
    - python -c "import xesmf; print(xesmf.__version__)"
  requires:
    - pip

about:
  home: https://github.com/pangeo-data/xESMF
  license: MIT
  license_file: LICENSE
  summary: Universal Regridder for Geospatial Data
  license_family: MIT

extra:
  recipe-maintainers:
    - ocefpaf
    - JiaweiZhuang
    - raphaeldussin
    - huard
