{% set version = "0.7.0" %}

package:
  name: xesmf
  version: {{ version }}

source:
  url: https://github.com/pangeo-data/xESMF/releases/download/v{{ version }}/xesmf-{{ version }}.tar.gz
  sha256: 61272d40669c47767fc3301550e4e8e936b049fda870f085488a7375f367c83b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools >=30.3.0
    - setuptools_scm
  run:
    - python >=3.6
    - esmpy >=8.0.0
    - xarray >=0.16.2
    - shapely
    - cf_xarray >=0.5.1
    - sparse >=0.8.0
    - numba

test:
  imports:
    - xesmf
  commands:
    - pip check
    - python -c "import xesmf; print(xesmf.__version__)"
  requires:
    - pip

about:
  home: https://github.com/pangeo-data/xESMF
  license: MIT
  license_file: LICENSE
  summary: Universal Regridder for Geospatial Data
  license_family: MIT

extra:
  recipe-maintainers:
    - ocefpaf
    - JiaweiZhuang
    - raphaeldussin
    - huard
